from app.models.usuario import Usuario
from app.models.estudiante import Estudiante
from app.models.instructor import Instructor
from app.models.grupo import Grupo
from app.models.grupo_estudiante import GrupoEstudiante
from app.models.trabajo import Trabajo
from app.models.entrega import Entrega
from app.models.calificacion import Calificacion
from app.models.asistencia import Asistencia
from app.models.notificacion import Notificacion